version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./sqldumps:/backups/mysql/wordpress/
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
  wordpress:
    links:
      - db
    image: wordpress:5.0.2-apache
    ports:
      - '8080:80'
    restart: always
    volumes:
      - .:/var/www/html/wp-content/themes/digihyppy
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      # - ./themes:/var/www/html/wp-content/themes/
      - ./blocks:/var/www/html/wp-content/plugins/digihyppy-blocks
      # - ./uploads:/var/www/html/wp-content/uploads/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    env_file:
      - ./.env
volumes:
  db_data: {}
